name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      
      - name: Debug Information
        run: |
          echo "Debugging deployment configuration"
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Working directory: $(pwd)"
          echo "Vercel project ID length: ${#VERCEL_BACKEND_PROJECT_ID}"
          echo "Vercel org ID length: ${#VERCEL_ORG_ID}"
          echo "Vercel token exists: $([[ -n "$VERCEL_TOKEN" ]] && echo 'Yes' || echo 'No')"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_BACKEND_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
          working-directory: ./backend
          vercel-args: '--prod'
          alias-domains: ''  # Set this if you want to specify a custom domain
        env:
          # The following environment variables will be set in Vercel project settings
          # You don't need to add these in the workflow if they're already set in Vercel
          VERCEL_ENV: production
